name: Dev Environment Plan

on:
  push:
    branches: [ main ]
    paths:
      - 'environments/dev/**'
      - 'modules/**'
      - '*.tf'
      - '*.tfvars'
  workflow_dispatch:

jobs:
  terraform-plan-dev:
    name: Terraform Plan - Dev Environment
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
        
    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Terraform Init
      run: |
        cd environments/dev
        terraform init
        
    - name: Terraform Plan
      id: plan
      run: |
        cd environments/dev
        terraform plan -out=tfplan -no-color
      continue-on-error: true
      
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: |
        echo "Terraform plan failed. Check the logs above for details."
        exit 1
        
    - name: Comment Plan on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const plan = fs.readFileSync('environments/dev/tfplan', 'utf8');
          
          const comment = `## 📋 Terraform Plan - Dev Environment
          
          <details>
          <summary>Show Plan</summary>
          
          \`\`\`terraform
          ${plan}
          \`\`\`
          </details>`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          
    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-dev
        path: environments/dev/tfplan
        retention-days: 30
