name: "Prod Terraform Apply"

on:
  workflow_run:   # 👈 dev-plan ke complete hone ke baad hi chalega
    workflows: ["Dev Terraform Plan"]
    types:
      - completed

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: prod   # 👈 yaha prod environment approval lagega
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: backendrg
          container_name: backendcontainer
          storage_account_name: backendstorge

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: environments/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: environments/prod
